import Head from 'next/head';

const SharedMeta: React.FC<{ title: string }> = ({ title }) => (
  <Head>
    <title>paycho | {title}</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

export default SharedMeta;
