import { Heading } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heading size="4xl">
        Testing this very loud thing and see if it works{' '}
      </Heading>

      <Heading size="4xl">
        Testing this very loud thing and see if it works{' '}
      </Heading>
      <Heading size="4xl">
        Testing this very loud thing and see if it works{' '}
      </Heading>
      <Heading size="4xl">
        Testing this very loud thing and see if it works{' '}
      </Heading>
      <Heading size="4xl">
        Testing this very loud thing and see if it works{' '}
      </Heading>

      <Heading size="4xl">
        Testing this very loud thing and see if it works{' '}
      </Heading>

      <Heading size="4xl">
        Testing this very loud thing and see if it works{' '}
      </Heading>
      <Heading size="4xl">
        Testing this very loud thing and see if it works{' '}
      </Heading>
      <Heading size="4xl">
        Testing this very loud thing and see if it works{' '}
      </Heading>
      <Heading size="4xl">
        Testing this very loud thing and see if it works{' '}
      </Heading>
      <main />
    </div>
  );
};

export default Home;
